apiVersion: v1
kind: PersistentVolume
metadata:
  name: notemplatevol
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data/"
    type: DirectoryOrCreate
