apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notemplatess
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
          subPathExpr: $(POD_NAME)
      volumes:
      - name: www
        persistentVolumeClaim:
          claimName: notemplateclaim